### PR TITLE
Update text domain

### PR DESCRIPTION
**Pull request by mayukojpn**
I realized this plugin doesn't support translation on WP.org: https://translate.wordpress.org/projects/wp-plugins/one-click-demo-import
Now text domain must match the slug of the plugin: https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/

### CODE REVIEW

**Comment by capuderg** [comment]
Hi @mayukojpn,

thanks for letting us know about this issue.

Did you use the grunt task `plugin_i18n ` for this change?

It looks like the domain path is also missing and the readme files has edits, which do not belong in this pull-request. Readme files only have examples, so there is no need to change anything there...

Could you please fix the above issues and I'll test this PR then.

Thank you and take care!

**Comment by mayukojpn** [comment]
Hi @capuderg ! Thank you for your feedback. I'm sorry but I don't think I have time to do more than that.

**Comment by capuderg** [comment]
Hi @mayukojpn ,

OK, then we'll sort this out before the next version of the plugin will be released.

**Comment by capuderg** [comment]
I'm closing this PR, since it's outdated. The text domain issue will be fixed in another branch (in the next plugin update).

**Pull request closed without merging**
